[tool.poetry]
name = "bone-remodeling"
version = "0.1.0"
description = "Package used to solve the inverse bone remodeling problem using reinforcement learning."
authors = ["gijsschlief <160142703+gijsschlief@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.7.0"
torchvision = "^0.22.0"
stable-baselines3 = {extras = ["extra"], version = "^2.6.0"}
scikit-image = "^0.25.2"
gym = "^0.26.2"
matplotlib = "^3.10.3"
numpy = "^2.2.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
mypy = "^1.5.0"
black = "^23.9.1"
ruff = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[mypy]
mypy_path = "."
ignore_missing_imports = true

[tool.ruff]
lint.select = [
  "F",    # Pyflakes: basic bugs
  "E",    # pycodestyle: style
  "W",    # pycodestyle: warnings
  "I",    # isort: import sorting
  "B",    # Bugbear: common mistakes
  "C4",   # flake8-comprehensions: better comprehensions
  "RUF",  # Ruff-specific fixes
  "D",    # Docstrings
  "DOC",  # Docstrings: PEP 257
  "ANN",  # Type annotations
  "T201", # print statements
  "PT",   # Pytest rules
  "SIM",  # Simplify
  "N",    # Naming conventions
]
lint.ignore = [
  "E501",    # Line length (Black/Ruff formatter handles this)
  "B008",    # Function call in default arg (valid for small projects)
  "D213",    # Multi-line docstring summary should start at the second line
  "D211",    # No blank lines allowed before class docstring
  "D203",    # 1 blank line required before class docstring
]